[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/index-v6.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-v1.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index-v6.html"
  status = 301
