[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/index-v13.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-v2.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index-v13.html"
  status = 301

[[redirects]]
  from = "/cancel"
  to = "/.netlify/functions/cancel-v1"
  status = 200

[[redirects]]
  from = "/reschedule"
  to = "/.netlify/functions/reschedule-v1"
  status = 200
